### ISSUE TITLE
Question: is it possible to submit data to the source url from $data?

### ISSUE THREAD

**Issue by Bhoft** [vitalets/x-editable-yii#40]
Hi i need a source url with get / post parameters for my EditableColumn of type 'select' because depending on some other column the selectable options are more or less.

is this somehow possible?
thx in advance regards Benjamin

**Comment by vitalets** [comment]
hi, please have a look on my comment in https://github.com/vitalets/x-editable-yii/issues/10#issuecomment-14006006
I plan some improvements, but it already should work on current version.

**Comment by vitalets** [comment]
since 1.3 you can define source as function that returns string, so you can construct url as you like:

``` php
'source'    => 'js: function() { return "?r=site/getStatusList"; }',
```

**Comment by Bhoft** [comment]
Can you please give an example?
Because i don't understand how this could produce what i wanted. 
I have a EditableColumn in my gridview
and depending on a "column" in my gridview eg. $data->status_id i wanted to have the options set for the editable column. 
And of course later the status_id will also be a editable column.

So if status_id is 1 the available options for the editable column should be 
'some option' , 'second option', 'third option'
and if status_id is 2 the options for the editable column should be 
'totally diffrent option' , 'yet another option'

So i need either a $_GET or $_POST parameter which i can give to the source url depending on which status_id is set in the current row for my editable column.
A dynamic paramter for the source url.

regards Horizons

**Comment by Bhoft** [comment]
Ok i can get the primary key like bewow and with it i can select the other required parameters in my source url action.

```
'source'    => 'js: function() {
                     var status_id=$(this).data().value;
                     var pk=$(this).data().pk;
                     return "?r=projectdetails/getProjectStatusList&status_id="+status_id+"&pk="+pk;
                 }',
```

Netherless it would be helpfull if additional parameters could be also given to the column.
e.g. if i wanted $data->created_by_id,$data->foreign_key as aditional parameters something like this

```
'additional_source_params=>'{"created_by_id":$data->created_by_id,"foreign_key":$data->foreign_key}' 
```

where that parameter is parsed the same way as the normal GridviewColumns to create a json array or something like that.

These values should be storeed the same as the pk. So that they could given to the source url as get parameters  automatically together with the current value and maybe the pk.

```
'source' => $this->createUrl('//projectdetails/getProjectStatusList'),
```

Maybe there is also some better idea?
Because i don't like to get other column data values with js code similar to this

```
$(this).closest('td').next().find('.editable');
```

which also doesn't work if that needed value isn't "shown" in the grid at all.

regards Horizons

**Comment by vitalets** [comment]
ok, I think we should divide into 3 cases:
**1.source url is totally defined at render time and doesn't change later:**
Here seems to be good just evalutate `source` url, e.g.

``` php
'source' => '"?r=projectdetails/getProjectStatusList&status_id=".$data->status_id."&pk=".$data->pk'
```

but it's currently NOT working, as `source` not evaluated. 
Maybe it has sence to add eval of source, but see no 3.

**2.source url is dynamic and depends on other editable columns that can be changed**
Here there is no other way to get value a-la 
`$(this).closest('td').next().find('.editable');`
because CGridView does not store data model itself, it's just representation of it.
In that case use js function returning url (as you shown)

**3.combination of 1 and 2:**
Part of url is static and depends on non-editable values, but another part is dynamic.
Here we still need use js function returning url, but somehow we should get access to other properties of $data.

I think the best solution for all cases is to add `data` property that will be evaluated into `data-*` attributes of cell.
It will be helpfull for all editable js functions that can more or less depend on other attributes of row model.

At the end the solution for most complex case 3 would be:

``` php
'editable' => array(
...
'data' => array(
  'created_by_id' => '$data->created_by_id', //will render in html as data-created_by_id="<id>"
),
'source' => ' js: function() {
  var created_by_id = $(this).data("created_by_id"); //static param
  var status_id = $(this).closest("td").next().find(".editable").value; //dynamic param
  return "/getProjectStatusList?cid=" + created_by_id + "&sid=" +status_id;
}',
...
)
```

I will try to do it for next release. 
but I'm a bit overloaded now, so it would greate if you make a pr for that ..

**Comment by Bhoft** [comment]
I would say its only combination one combination of 1,2 or 1+2
eg. it could also be something that the available options could depend on a normal gridview column / data which even musn't been rendered at all (e.g. primary key or foreign key coulumns).
But the data would be available through $data->column_name on render of the editable column. 

But as you mentioned in your third possibility this would also be possible to "store" the data in this case.

It would even help more if the source url wouldn't have to be generated with js. 
And just attach the stored "data" values as $_GET parameters in the order they have been defined if set.

So it would only need

```
'source' => $this->createUrl('//controller/getStatusList'),
 'data' => array( 
'id' => '$data->primary_key',
 'created_by_id' => '$data->created_by_id',
...
 ),
```

and the requested source url would automatically be 

```
/controller/getStatusList?id=primary_keyvalue&created_by_id=created_by_idvalue
```

I will see if i have the time to see if this is feasible. But i have never used github and created a pull request. Gues i have to create a fork first and reupload my changed code. i will see if i have the time for this. 
but currently i use the pk as get and just use findbyPk to get my needed values to return the available options.
